import java.util.Scanner;

public class GestorEstudiantes {
    
    static int contadorEstudiantes = 0;
    final static int ANO_EN_CURSO = 2023;

    public void anadirEstudiante(Estudiante [] estudiantes) throws InterruptedException {

        Scanner sc = new Scanner (System.in);

        String inputNombre = "";
        String inputApellidos = "";
        int inputEdad = 0;

        System.out.print("Introduce el nombre del alumno: ");
        inputNombre = sc.nextLine();
        System.out.print("Introduce los apellidos del alumno: ");
        inputApellidos = sc.nextLine();
        System.out.print("Introduce la edad del alumno: ");
        inputEdad = sc.nextInt();

        System.out.println("Generando email...");
        Thread.sleep(1000);

        String autoGeneratedEmail = inputApellidos.toLowerCase() + "." + inputNombre.toLowerCase() + (ANO_EN_CURSO - inputEdad) + "@tiernoparla.es"; // Variable que almacena un email generado a partir del nombre y de la edad 

        System.out.println("Verificando email...");
        if(autoGeneratedEmail.substring(1).contains("@")) { // Condición de que el email contenga una @
            System.out.println("Email verificado correctamente");
            Thread.sleep(1000);
            System.out.println("El email generado para dicho alumno es: " + autoGeneratedEmail);
            Estudiante e = new Estudiante(inputNombre, inputApellidos, inputEdad, autoGeneratedEmail);
            estudiantes[contadorEstudiantes] = e;
            System.out.println("Alumno registrado con éxito");
            contadorEstudiantes++;  // Quizás haya que añadir esta variable en el main
        } else {
            System.out.println("El email generado no es válido");
        }

    }

    public void visualizarEstudiantes(Estudiante [] estudiantes) {
        for (int i = 0; i < estudiantes.length; i++) {
            System.out.println(estudiantes[i].toString());
        }
    }

    public void buscarPorEmail(Estudiante [] estudiantes) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Introduce un email para realizar la búsqueda: ");
        String inputEmail = sc.nextLine();

        for (int i = 0; i < estudiantes.length; i++) {
            if(inputEmail.equals(estudiantes[i].getEmail())) {
                System.out.println("Alumno encontrado: " + estudiantes[i].getNombre() + " " + estudiantes[i].getApellido());
            } else {
                System.out.println("Alumno no registrado en el sistema");
            }
        }
    }

}
